### ISSUE TITLE
libguile-gpgme 

### ISSUE THREAD

**Issue by nicolas-graves** [xatom/gpgme-with-guile#3]
Hi again ! 

I'm trying to understand how the package is built. My ultimate goal is to make is working to use it in my dotfiles, and to get it to function as a proper guix package (basically to be able to call gpg directly from .scm source code).  

I get a code error when trying to pass it through `guile-build-system`, which is linked  to the local link you left to `libguile-gpgme`, used with the `*debug*` variable. 

My guess was that it was a library generated from the file `src/lib/gpgme-wrapper.c`. I'm not experienced in C at all, but I tried to get it by running the following commands (don't mind the guix syntax) : 

```
gcc -c -I /gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/include/guile/3.0 gpgme_wrapper.c
gcc -L /gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/lib -L /gnu/store/33x095pip87pxcn23cz8k96jq6bka51s-gpgme-1.15.1/lib -l guile-3.0 -l gpgme gpgme_wrapper.o
```
But I'm stuck with the following error on that second command : 
```
ld: /home/graves/.guix-profile/lib/crt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

Do you remember how you managed to get your `libguile-gpgme` library ?

**Comment by nicolas-graves** [comment]
Also if you what to take a look and help with the guix package definition, I was working for it here : https://github.com/nicolas-graves/guix-channel/blob/master/ngraves/packages/guile-gpgme.scm

**Comment by nicolas-graves** [comment]
```
gcc -Wextra -c -I /gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/include/guile/3.0 -fPIC -o libguile-gpgme.so -shared -L /gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/lib -L /gnu/store/33x095pip87pxcn23cz8k96jq6bka51s-gpgme-1.15.1/lib -L /gnu/store/pilv2s68v4xamxwk1ahfy7q32j6wnf7l-libgpg-error-1.42/lib -l guile-3.0 -l gpgme -l gpg-error gpgme_wrapper.c
```
seems to work, I'll try with that

**Comment by xatom** [comment]
Hi @nicolas-graves,
That mile-long `gcc` incantation you came up with was more-or-less what I was doing while I was developing this many years ago. Indeed, `gpgme-wrapper.c` is the source for a minimalist library meant to bridge the GPGME shared library to Guile and also initialize it for use in Scheme code. It is not complete by any means, but I believe the call to `gpg_get_engine_info()` does initialize the library on the C-side, and allows the Guile FFI to begin using the code properly.

**Edit**: y'know what, I think I'm wrong about this, and was thinking of a completely separate binding I worked on. The `libguile-gpgme` helper library here was created to encapsulate GPGME's imperative style and variable mutation, shielding the Scheme library from it and presenting a more functional interface. The only use that I'd come to at the point development stopped was wrapping `gpgme_get_engine_info ()` for use in the `(gpg protocols)` module.

**Comment by xatom** [comment]
There's also the fact that this project sat for more than 8 years before today; the last time I touched it was back in the Guile 2.2 days (or was that Guile 2.0?) You've already run into an issue with your pull request  [merged here](url). Luckily, I never really got that far with this project, so such corrections like this are hopefully few.

**Comment by xatom** [comment]
As for building the package, I think utilizing Guix is the way to go.  I'm not an expert with Guix at all (I run it on a foreign distro, but haven't had a chance to dive in properly,) so I'm happy to try and get your package definition working and go from there. The goal in the beginning was to get basic functionality working with hand compilation, then implement an autotools-based build system for the project.  Now with guix providing the basic framework for doing just that (rather than cobbling it together from adapting C projects back in 2015), it seems like now is the time to work on that.

Just to get it down for reference, there are a few things that need to happen with the build:

- `libguile-gpgme` needs to be built and installed (should build like any C library under Guix with a dependency on libguile)
- `error-code-snarf.scm` needs to be executed to generate both `src/gpg/error-codes.scm` and `src/gpg/error-sources.scm` from their respective `*.in` files
- `(gpg ...)` modules need to be compiled and installed

**Comment by nicolas-graves** [comment]
I finally got the packaging part to work, haven't tested yet and won't have the time today, it is in the link I gave earlier. 
Would you be able to add a quick description of how to use the package, even if incomplete, in the README ? I've seen that there are some long commentary in the source code, but don't have an overall view yet :) 

Thanks for the work on that ;)
If everything works fine, I'll contribute directly to the guile source code.

**Comment by nicolas-graves** [comment]
I don't plan further work on this, closing the issue.
